.PHONY: build

# ============================================================================ #
# BUILD COMMANDS
# ============================================================================ #

build:
	python -m build --no-isolation --wheel \
		--config-setting 'variant-property=fictional_hw :: architecture :: mother' \
		--config-setting 'variant-property=fictional_hw :: compute_accuracy :: 10'
